name: ros2_template

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      ros_distro:
        required: true
        type: string

jobs:
  colcon-build:
    name: build
    runs-on: ubuntu-latest

    container:
      image: rostooling/setup-ros-docker:${{ inputs.base }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: rmcl
          target-ros2-distro: ${{ inputs.ros_distro }}
          vcs-repo-file-url: $GITHUB_WORKSPACE/source_dependencies.yaml
          rosdep-check: true
