name: ros2_jazzy

on:
  push:
    branches:
      - 'ros-workflows'
  pull_request:
    branches:
      - 'ros-workflows'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  humble:
    name: ros2-humble
    uses: ./.github/workflows/ros2_template.yml
    with:
      base_docker: rostooling/setup-ros-docker:ubuntu-jammy-latest
      ros_distro: humble
